name: 'Terraform'

on:
  push:
    branches:
    - main

env:
  AWS_REGION: 'us-west-2'  # Customize this
  TF_VAR_region: 'us-west-2'  # Customize this
  TF_ACTION_WORKING_DIR: '.'
  TF_BACKEND_BUCKET_NAME: 'my-tfstate-bucket-guedson'  # Customize this
  TF_BACKEND_KEY: 'terraform.tfstate'
  TF_VERSION: 'latest'
  TF_WORKSPACE: 'default'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Terraform Init'
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}
        terraform_version: ${{ env.TF_VERSION }}
        terraform_wrapper: true

    - name: 'Terraform Format'
      id: fmt
      run: terraform fmt -check

    - name: 'Terraform Init'
      id: init
      run: terraform init

    - name: 'Terraform Validate'
      id: validate
      run: terraform validate -no-color

    - name: 'Terraform Plan'
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -no-color
